//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceData
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public string DepartmentName { get; set; }
        public string UserLeavePolicyID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> FirstPunchIn { get; set; }
        public Nullable<System.DateTime> LastPunchOut { get; set; }
        public Nullable<long> TotalWorkHours { get; set; }
        public Nullable<long> BreakHours { get; set; }
        public Nullable<bool> IsLateArrival { get; set; }
        public Nullable<bool> IsEarlyDeparture { get; set; }
        public Nullable<bool> IsAbsent { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public string LeaveType { get; set; }
        public Nullable<bool> IsLeave { get; set; }
        public string ManagerEmail { get; set; }
        public string CountryName { get; set; }
        public string Manager2Email { get; set; }
        public Nullable<int> BioStarEmpNum { get; set; }
        public string UserID { get; set; }
        public string DepartmentID { get; set; }
        public string DEVID { get; set; }
        public string ManagerId { get; set; }
        public string Manager2Id { get; set; }
        public string Devnm { get; set; }
        public string TimeZone { get; set; }
    }
}
