//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakHour
    {
        public int BreakHoursID { get; set; }
        public string UserId { get; set; }
        public Nullable<int> BioStarEmpNum { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public System.DateTime PunchIn { get; set; }
        public System.DateTime PunchOut { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
