//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentName
    {
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string HRBPEmail { get; set; }
        public Nullable<int> HRBPBiostarEmpNum { get; set; }
        public Nullable<int> HODID { get; set; }
        public Nullable<int> HRBPID { get; set; }
    
        public virtual tblHRBP tblHRBP { get; set; }
    }
}
