//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Monthly_Leaves_Report
    {
        public string UserName { get; set; }
        public string LeaveType { get; set; }
        public string Reason { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<decimal> TotalDays { get; set; }
        public string EmergencyContact { get; set; }
        public string HrManager { get; set; }
        public string ManagerOne { get; set; }
        public string ManagerTwo { get; set; }
        public Nullable<int> IsAcceptedHr { get; set; }
        public Nullable<int> IsAccepted1 { get; set; }
        public Nullable<int> IsAccepted2 { get; set; }
        public string RemarksHr { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
