//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure;

namespace Repository.Models
{
 
    using System.Data.Entity.Core.Objects;
  
    using System.Web;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Threading.Tasks;


 
   
 
 

    public partial class LeaveONEntities : DbContext
    {
        public LeaveONEntities()
            : base("name=LeaveONEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<AnnualLeaveManager> AnnualLeaveManagers { get; set; }
        public virtual DbSet<AnnualOffDay> AnnualOffDays { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<CountryName> CountryNames { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<UserLeavePolicyDetail> UserLeavePolicyDetails { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<AttendanceData> AttendanceDatas { get; set; }
        public virtual DbSet<BreakHour> BreakHours { get; set; }
        public virtual DbSet<HR_Monthly_Leaves_Report> HR_Monthly_Leaves_Report { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<UserLeavePolicy> UserLeavePolicies { get; set; }
        public virtual DbSet<LeaveBalance> LeaveBalances { get; set; }
        public virtual DbSet<tblHRBP> tblHRBPs { get; set; }
        public virtual DbSet<DepartmentName> DepartmentNames { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }


        //public override int SaveChangesAsync()
        public override async Task<int> SaveChangesAsync()
        {
            int result;
            List<AuditLog> auditLogs;
            BindLogs(out result, out auditLogs);

            if (auditLogs.Any())
            {
                AuditLogs.AddRange(auditLogs);
                base.SaveChanges();
            }

            return result;
        }

        private void BindLogs(out int result, out List<AuditLog> auditLogs)
        {
            ChangeTracker.DetectChanges();

            var entries = ChangeTracker.Entries()
                            .Where(e =>
                                !(e.Entity is AuditLog) &&
                                (e.State == EntityState.Added ||
                                 e.State == EntityState.Modified ||
                                 e.State == EntityState.Deleted))
                            .ToList();

            var auditData = new List<AuditData>();

            foreach (var entry in entries)
            {
                var propertyValues = new Dictionary<string, (object, object)>();

                if (entry.State == EntityState.Modified)
                {
                    // Pull the TRUE original row from the database, untracked,
                    // because the in-memory OriginalValues is unreliable for
                    // disconnected/attached entities.
                    var dbValues = entry.GetDatabaseValues();

                    if (dbValues != null)
                    {
                        foreach (var propertyName in entry.CurrentValues.PropertyNames)
                        {
                            object oldValue = dbValues[propertyName];
                            object newValue = entry.CurrentValues[propertyName];
                            propertyValues[propertyName] = (oldValue, newValue);
                        }
                    }
                }
                else if (entry.State == EntityState.Added)
                {
                    foreach (var propertyName in entry.CurrentValues.PropertyNames)
                        propertyValues[propertyName] = (null, entry.CurrentValues[propertyName]);
                }
                else if (entry.State == EntityState.Deleted)
                {
                    foreach (var propertyName in entry.OriginalValues.PropertyNames)
                        propertyValues[propertyName] = (entry.OriginalValues[propertyName], null);
                }

                auditData.Add(new AuditData
                {
                    Entry = entry,
                    TableName = GetTableName(entry),
                    Action = GetAction(entry.State),
                    ScreenName = GetScreenName(),
                    UserId = GetUserId(),
                    PropertyValues = propertyValues
                });
            }

            result = base.SaveChanges();

            auditLogs = new List<AuditLog>();
            foreach (var audit in auditData)
            {
                string recordId = GetPrimaryKeyValue(audit.Entry);

                foreach (var kvp in audit.PropertyValues)
                {
                    var propertyName = kvp.Key;
                    var oldValue = kvp.Value.Item1;
                    var newValue = kvp.Value.Item2;

                    if (audit.Action == "Modified" && object.Equals(oldValue, newValue))
                        continue;

                    auditLogs.Add(new AuditLog
                    {
                        TableName = audit.TableName,
                        RecordId = recordId,
                        Action = audit.Action,
                        ScreenName = audit.ScreenName,
                        ColumnName = propertyName,
                        OldValue = ConvertToString(oldValue),
                        NewValue = ConvertToString(newValue),
                        UserId = audit.UserId,
                        AuditDate = DateTime.Now
                    });
                }
            }
        }

        public override int SaveChanges()
        { // Get all entities that are being Added, Modified or Deleted
            int result;
            List<AuditLog> auditLogs;
            BindLogs(out result, out auditLogs);

            // Save audit records
            if (auditLogs.Any())
            {
                AuditLogs.AddRange(auditLogs);

                // Save audit records
                base.SaveChanges();
            }

            return result;
        }


        // ============================================================
        // Get Action
        // ============================================================

        private string GetAction(EntityState state)
        {
            switch (state)
            {
                case EntityState.Added:
                    return "Added";

                case EntityState.Modified:
                    return "Modified";

                case EntityState.Deleted:
                    return "Deleted";

                default:
                    return "";

            }
        }
        // ============================================================
        // Get Table Name
        // ============================================================

        private string GetTableName(DbEntityEntry entry)
        {
            var objectContext =
                ((IObjectContextAdapter)this).ObjectContext;

            var objectType =
                ObjectContext.GetObjectType(entry.Entity.GetType());

            var entityType =
                objectContext.MetadataWorkspace
                    .GetItems<System.Data.Entity.Core.Metadata.Edm.EntityType>(
                        System.Data.Entity.Core.Metadata.Edm.DataSpace.CSpace)
                    .FirstOrDefault(x => x.Name == objectType.Name);

            if (entityType != null)
            {
                return entityType.Name;
            }

            return objectType.Name;
        }

        // ============================================================
        // Get Primary Key / Record ID
        // ============================================================

        private string GetPrimaryKeyValue(DbEntityEntry entry)
        {
            var objectContext =
                ((IObjectContextAdapter)this).ObjectContext;

            var objectType =
                ObjectContext.GetObjectType(entry.Entity.GetType());

            var entityType =
                objectContext.MetadataWorkspace
                    .GetItems<System.Data.Entity.Core.Metadata.Edm.EntityType>(
                        System.Data.Entity.Core.Metadata.Edm.DataSpace.CSpace)
                    .FirstOrDefault(x => x.Name == objectType.Name);

            if (entityType == null)
            {
                return "";
            }

            var keyValues = new List<string>();

            foreach (var keyProperty in entityType.KeyProperties)
            {
                object value;

                if (entry.State == EntityState.Deleted)
                {
                    value = entry.OriginalValues[keyProperty.Name];
                }
                else
                {
                    value = entry.CurrentValues[keyProperty.Name];
                }

                keyValues.Add(ConvertToString(value));
            }

            return string.Join(",", keyValues);
        }


        // ============================================================
        // Get Controller / Action
        // ============================================================

        private string GetScreenName()
        {
            try
            {
                //return "System";
                var httpContext =   HttpContext.Current;

                if (httpContext == null)
                {
                    return "System";
                }

                var routeData =
                    httpContext.Request.RequestContext.RouteData;

                var controller =
                    routeData.Values["controller"]?.ToString();

                var action =
                    routeData.Values["action"]?.ToString();

                if (!string.IsNullOrEmpty(controller) &&
                    !string.IsNullOrEmpty(action))
                {
                    return controller + "/" + action;
                }

                return controller ?? "Unknown";
            }
            catch
            {
                return "Unknown";
            }
        }


        // ============================================================
        // Get Current User
        // ============================================================

        private string GetUserId()
        {
            try
            {
                 
                 var user  =  HttpContext.Current?.User;

                if (user != null &&
                    user.Identity != null &&
                    user.Identity.IsAuthenticated)
                {
                    return user.Identity.Name;
                }

                return "System";
            }
            catch
            {
                return "System";
            }
        }


        // ============================================================
        // Convert Value to String
        // ============================================================

        private string ConvertToString(object value)
        {
            if (value == null)
            {
                return null;
            }

            return Convert.ToString(value);
        }

        // ============================================================
        // Helper class
        // ============================================================

       
        private class AuditData
        {
            public DbEntityEntry Entry { get; set; }

            public string TableName { get; set; }

            public string Action { get; set; }

            public string ScreenName { get; set; }

            public string UserId { get; set; }
            public Dictionary<string, (object OldValue, object NewValue)> PropertyValues { get; set; }

        }
    }
}