//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public string UserID { get; set; }
        public Nullable<int> BioStarEmpNum { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
    }
}
