//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLeavePolicyDetail
    {
        public decimal Id { get; set; }
        public Nullable<int> UserLeavePolicyId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public Nullable<int> Allowed { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual UserLeavePolicy UserLeavePolicy { get; set; }
    }
}
