//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BioStarEntities : DbContext
    {
        public BioStarEntities()
            : base("name=BioStarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UD_TB_AccessTime_Data> UD_TB_AccessTime_Data { get; set; }
        public virtual DbSet<UD_TB_AD_USER> UD_TB_AD_USER { get; set; }
    }
}
