//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_TB_AccessTime_Data
    {
        public decimal EventLogID_IN { get; set; }
        public decimal EventLogID_OUT { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> Date_IN { get; set; }
        public string Day_IN { get; set; }
        public Nullable<System.DateTime> Time_IN { get; set; }
        public Nullable<int> ReaderID_IN { get; set; }
        public string DeviceName_IN { get; set; }
        public Nullable<System.DateTime> Date_OUT { get; set; }
        public string Day_OUT { get; set; }
        public Nullable<System.DateTime> Time_OUT { get; set; }
        public Nullable<int> ReaderID_OUT { get; set; }
        public string DeviceName_OUT { get; set; }
        public Nullable<int> Duration { get; set; }
    }
}
