//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_TB_AD_USER
    {
        public decimal EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public string SAM { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public string Company { get; set; }
        public Nullable<bool> IsUSEmp_Five_Year_Plus { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string EmpCompany { get; set; }
    }
}
