// <auto-generated />
namespace LeaveON.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class countryName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(countryName));
        
        string IMigrationMetadata.Id
        {
            get { return "202107061610303_countryName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
