// <auto-generated />
namespace LeaveON.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Department1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Department1));
        
        string IMigrationMetadata.Id
        {
            get { return "202106161304069_Department1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
